apiVersion: v1
kind: Service
metadata:
  name: microservicio-seguridad
spec:
  selector:
    app: microservicio-seguridad
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP