name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PASSWORD}}
        ecr: auto
        logout: true
          
    - name: Build the Docker image
      run: docker build --build-arg JWT_SECRETO=${{ secrets.JWT_SECRETO }} --build-arg DB_URL=${{ secrets.DB_URL }} --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} --build-arg MICROSERVICIO_REGISTRO_URI=${{ secrets.MICROSERVICIO_REGISTRO_URI }} -t ${{secrets.DOCKER_HUB_USERNAME}}/ec-seguridad:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/ec-seguridad:latest
